version: "1.0"
info:
  model: int-scaffold
packages:
- name: ISR_AvivSim_DADA_WT_DEMOProject
  gitServerName: AvivSim_Github
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: main
- name: OpenWeatherClient
  gitServerName: AvivSim_Github
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: AvivSimDS
  gitBranch: main
services:
- serviceName: project.isr_avivsim_dada_wt_demo.integrations:HelloWorld
  packages:
  - name: ISR_AvivSim_DADA_WT_DEMOProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
