version: "1.0"
info:
  model: int-scaffold
packages:
- name: ISR_AvivSim_DADA_WT_DEMOProject
  gitServerName: AvivSim_Github
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: main
- name: OpenWeatherClient
  version: "1.0"
  gitServerName: AvivSim_Github
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: AvivSimDS
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
- name: PayableTransactions
  version: "1.0"
  gitServerName: AvivSim_Github
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: main
services:
- serviceName: project.isr_avivsim_dada_wt_demo.integrations:InvokePayableTransactionsPkgServices
  packages:
  - name: ISR_AvivSim_DADA_WT_DEMOProject
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
  - name: PayableTransactions
    version: "1.0"
- serviceName: PayableTransactionsPackage.adapterServices:allPayableUsers
  packages:
  - name: PayableTransactions
    version: "1.0"
configurationVariables:
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.poolable
  : "true"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.serverName
  : localhost
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.dbType
  : MySQL
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.databaseName
  : poalim_current_accounts_db
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.keyStore
  : ""
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.networkProtocol
  : ""
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.driverType
  : mysql_driver
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.portNumber
  : "3306"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.user
  : root
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionEnabled
  : "false"
  ? artConnection.ISR_AvivSim_DADA_WT_DEMOProject.project.isr_avivsim_dada_wt_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AccountsLocalDB.connectionSettings.trustStore
  : ""
